services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: forum_db
      MYSQL_USER: everton
      MYSQL_PASSWORD: 12124444
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-net

networks:
  spring-net:

volumes:
  mysql_data:
